import {api,message} from './api.js';
import {$,$$,esc,title,header,notice,field,toast} from './ui.js';

export async function showAcquisition(container,ctx){
  const data=await api('/acquisition');
  container.innerHTML=header('Acquisition','Local files, retained evidence, and separate staff review.', '<button id="refresh-acquisition" class="secondary">Refresh status</button>')+
    notice('Download provider files into your chosen folder. Watching runs only while UtilityOS is open. It starts disabled after every application restart. Invoices and operational usage always need separate approval.')+
    `<section class="panel"><h2>Watched folder</h2><p id="watcher-state" role="status"><strong>${esc(title(data.state))}</strong>${data.processing?' · Finishing one file':''} · Checks every ${data.poll_seconds} seconds · No subfolders</p>${data.error?notice(message(data.error),'danger'):''}<p class="source-hash">${esc(data.directory||'No folder configured')}</p><p class="caption">Last check: ${esc(data.last_poll||'Not checked this session')}. Last retained file: ${esc(data.last_success||'None this session')}.</p><form id="acquisition-folder">${field('Local acquisition folder','directory',data.directory,'text','maxlength="2048" placeholder="Choose an existing local folder"')}<label class="check-label"><input id="acquisition-folder-ack" type="checkbox" required><span>I confirm this is a separate authorized local folder containing ${ctx.mode==='demo'?'synthetic':'authorized'} downloads.</span></label><button type="submit" class="secondary" ${data.state!=='disabled'||data.processing?'disabled':''}>Save acquisition folder</button></form><p class="caption">Disable watching before changing the folder. Files are read without moving, editing or deleting them. A file already being processed can finish after pause or disable.</p><label class="check-label"><input id="watcher-ack" type="checkbox"><span>I authorize intake of ${ctx.mode==='demo'?'synthetic':'authorized'} files from the displayed folder while UtilityOS is running.</span></label><div class="action-row">${data.state==='watching'?'<button class="secondary" data-watch-action="pause">Pause watching</button>':`<button class="primary" data-watch-action="${data.state==='paused'?'resume':'enable'}" ${data.directory?'':'disabled'}>${data.state==='paused'?'Resume watching':'Enable watching'}</button>`}${data.state!=='disabled'?'<button class="secondary" data-watch-action="disable">Disable watching</button>':''}</div><div id="acquisition-error" aria-live="polite"></div></section>`+
    `<section class="panel table-panel"><h2>Source processing</h2><p class="caption">Pending counts include all retained sources, including direct usage uploads. Error history covers the latest 200 intake attempts. Repeated copies keep one retained source. Refresh to see new arrivals.</p><div class="table-scroll"><table><thead><tr><th>Source / mode</th><th>Last file</th><th>Last retained</th><th>Pending review</th><th>Errors</th></tr></thead><tbody>${data.sources.map(s=>`<tr><td>${esc(s.label)}<small>${s.kind==='financial'?'Financial review':'Operational review'}</small></td><td>${esc(s.last_file||'No file')}<small>${esc(s.last_attempt||'')}</small></td><td>${esc(s.last_success||'—')}</td><td>${s.pending_review}</td><td>${s.errors}</td></tr>`).join('')}<tr><td>ENERGY STAR Portfolio Manager<small>Connector disabled</small></td><td colspan="4">School authorization, meter coverage, transfer conditions and fees must be confirmed before external synchronization.</td></tr></tbody></table></div><div class="action-row"><button id="acquisition-invoices" class="secondary">Review invoices and XML</button><button id="acquisition-usage" class="secondary">Review mapped usage</button></div></section>`+
    `<section class="panel"><h2>Recent files requiring attention</h2>${data.history.filter(r=>['failed_safely','unsupported','needs_review','needs_mapping'].includes(r.state)).slice(0,25).map(r=>`<p><strong>${esc(r.filename)}</strong> · ${esc(title(r.state))}${r.code?` · ${esc(message(r.code))}`:''}</p>`).join('')||'<p>No recent files need attention.</p>'}<p class="caption">To retry a failed unchanged file, use the explicit scan in Utility Inbox. Unsupported files remain in the download folder.</p><button id="acquisition-inbox" class="secondary">Open Utility Inbox</button></section>`+
    `<section class="panel"><h2>Portable health check</h2><p>Checks this installation using fixed health categories, with no private records or file paths.</p><button id="acquisition-health" class="secondary">Check installation health</button><div id="acquisition-health-result" aria-live="polite"></div></section>`;
  $('#refresh-acquisition').onclick=()=>ctx.refresh('acquisition');
  $('#acquisition-invoices').onclick=()=>ctx.navigate('review');
  $('#acquisition-usage').onclick=()=>ctx.navigate('usage');
  $('#acquisition-inbox').onclick=()=>ctx.navigate('inbox');
  $('#acquisition-folder').onsubmit=async event=>{event.preventDefault();const button=$('button',event.currentTarget);button.disabled=true;try{await api('/intake/configuration',{method:'POST',body:{directory:$('[name=directory]',event.currentTarget).value,acknowledge:$('#acquisition-folder-ack').checked}});toast('Acquisition folder saved.');await ctx.refresh('acquisition');}catch(error){$('#acquisition-error').innerHTML=notice(message(error.message),'danger');button.disabled=false;}};
  $$('[data-watch-action]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await api('/acquisition/control',{method:'POST',body:{action:button.dataset.watchAction,directory:data.directory,acknowledge:$('#watcher-ack').checked,synthetic:ctx.mode==='demo'}});await ctx.refresh('acquisition');}catch(error){$('#acquisition-error').innerHTML=notice(message(error.message),'danger');button.disabled=false;}});
  $('#acquisition-health').onclick=async()=>{const target=$('#acquisition-health-result');target.textContent='Checking local installation…';try{const report=await api('/health');if(target.isConnected)target.innerHTML=`<pre class="diagnostics acquisition-health-report">${esc(JSON.stringify(report,null,2))}</pre>`;}catch(error){if(target.isConnected)target.innerHTML=notice(message(error.message),'danger');}};
}
