import {api,message} from './api.js';
import {$,$$,esc,title,header,field,selectField,notice,toast} from './ui.js';

export async function showCompleteness(container,ctx,selected){
  const data=await api(`/completeness${selected?'?month='+encodeURIComponent(selected):''}`),inventory=await api('/inventory');
  const links=inventory.account_meters.filter((link,i,all)=>all.findIndex(x=>x.account_id===link.account_id&&x.meter_id===link.meter_id)===i);
  container.innerHTML=header('Bill completeness','Preparation view based on explicitly confirmed invoice-month expectations.')+
    notice('Experimental coverage view. This is not authoritative campus completeness. Delivery and irregular accounts are not marked missing. Received means an active approved bill or a mapped pending draft; rejected drafts do not count.','warning')+
    `<div class="action-row">${field('Invoice month','coverage-month',data.month,'month')}<button class="secondary" id="coverage-update">Show month</button></div>`+
    `<section class="coverage-counts">${Object.entries(data.counts).map(([key,value])=>`<div class="panel"><span>${esc(title(key))}</span><strong>${value}</strong></div>`).join('')}</section>`+
    `<section class="panel table-panel"><div class="table-scroll"><table><thead><tr><th>Service / account</th><th>Cadence</th><th>State</th></tr></thead><tbody>${data.rows.map(row=>`<tr><td>${esc(row.meter_code)}<small>${esc(row.provider)} · ${esc(row.account_alias)}</small></td><td>${esc(title(row.cadence))}</td><td>${esc(title(row.state))}${row.also_under_review?' · replacement also under review':''}</td></tr>`).join('')}</tbody></table></div>${data.rows.length?'':notice('No active expectations for this month. Confirm a relationship and cadence below; observed bills alone do not establish coverage.')}</section>`+
    `<details class="panel"><summary>Confirm an expected account and service cadence</summary><p>Choose a relationship already reviewed in the utility inventory. Specify the invoice months in which bills are expected. This changes coverage expectations, not approved charges.</p><form id="coverage-config">${selectField('Account / service relationship','coverage-link',[['','Select a confirmed relationship'],...links.map((link,i)=>{const account=inventory.accounts.find(a=>a.id===link.account_id),meter=inventory.meters.find(m=>m.id===link.meter_id);return [String(i),`${account.provider} · ${account.alias} · ${meter.code}`];})],'')}${selectField('Expected cadence','cadence',[['monthly','Monthly bill'],['delivery','Delivery-based invoice'],['irregular','Irregular bill']],'monthly')}<div class="form-grid two">${field('First invoice month','first_month',data.month,'month')}${field('Last invoice month (optional)','last_month','','month')}</div><label class="check-label"><input type="checkbox" id="coverage-enabled" checked><span>Expectation is active</span></label>${field('Reason for coverage decision','coverage-reason','','text','required maxlength="500"')}<label class="check-label"><input type="checkbox" id="coverage-ack" required><span>I confirmed this cadence and date range; incomplete historical coverage remains possible.</span></label><button class="primary" type="submit">Save expectation</button><div id="coverage-error"></div></form></details>`;
  $('#coverage-update').onclick=()=>ctx.refresh('completeness',$('[name=coverage-month]').value);
  $('[name=coverage-link]').onchange=e=>{const link=links[Number(e.target.value)],before=data.configuration.find(x=>x.account_id===link?.account_id&&x.meter_id===link?.meter_id);$('[name=cadence]').value=before?.cadence||'monthly';$('[name=first_month]').value=before?.first_month||data.month;$('[name=last_month]').value=before?.last_month||'';$('#coverage-enabled').checked=before?Boolean(before.enabled):true;};
  $('#coverage-config').onsubmit=async e=>{e.preventDefault();try{const chosen=$('[name=coverage-link]').value;if(chosen==='')throw new Error('CONFIRMED_ACCOUNT_METER_RELATIONSHIP_REQUIRED');const link=links[Number(chosen)],before=data.configuration.find(x=>x.account_id===link.account_id&&x.meter_id===link.meter_id);await api('/completeness',{method:'POST',body:{account_id:link.account_id,meter_id:link.meter_id,revision:before?.revision||0,cadence:$('[name=cadence]').value,first_month:$('[name=first_month]').value,last_month:$('[name=last_month]').value,enabled:$('#coverage-enabled').checked,reason:$('[name=coverage-reason]').value,acknowledge:$('#coverage-ack').checked}});toast('Expectation saved.');ctx.refresh('completeness',data.month);}catch(error){$('#coverage-error').innerHTML=notice(message(error.message),'danger');}};
}
