import {api,message} from './api.js';
import {$,$$,esc,title,header,field,notice,toast} from './ui.js';

export async function showInbox(container,ctx){
  const data=await api('/intake');
  container.innerHTML=header('Utility Inbox','Supply downloaded files locally. Every invoice waits for staff review.',`<button class="primary" id="intake-picker">Import files</button>`)+
    notice('Digital PDFs use local extraction and tested templates. Scans can use the optional local OCR model. No document is sent to an external service.')+
    `<details class="panel"><summary>Optional local inbox directory</summary><p>Select a separate folder you control, outside this code folder and the ledger workspace. Files stay in that folder. Scan Inbox reads up to 25 completed CSV, XML or PDF files; it does not watch in the background.</p><form id="inbox-config">${field('Local UtilityOS Inbox directory','directory',data.configuration.directory,'text','placeholder="/approved/local/UtilityOS Inbox" maxlength="2048"')}<label class="check-label"><input type="checkbox" id="inbox-location-ack" required><span>I confirm this is an authorized local folder containing ${ctx.mode==='demo'?'synthetic':'authorized'} files.</span></label><button class="secondary" type="submit">Save inbox location</button><div id="inbox-config-error"></div></form></details>`+
    `<section class="panel"><h2>Explicit scan</h2><p class="source-hash">${esc(data.configuration.directory||'No inbox directory configured. File picker and drag-and-drop remain available.')}</p><label class="check-label"><input type="checkbox" id="inbox-scan-ack"><span>I confirm this displayed folder and its ${ctx.mode==='demo'?'synthetic':'authorized'} files should be scanned now.</span></label><button class="secondary" id="scan-inbox" ${data.configuration.directory?'':'disabled'}>Scan Inbox</button><div id="scan-results" aria-live="polite"></div></section>`+
    `<section class="panel"><h2>Intake history</h2><p class="caption">Latest 200 attempts. A duplicate opens the retained review; it does not create another invoice. Failed extraction can still open a manual draft when its source was retained.</p><div class="table-scroll"><table><thead><tr><th>Local file</th><th>State</th><th>Details</th><th>Review</th></tr></thead><tbody>${data.items.map(item=>`<tr><td>${esc(item.filename)}<small>${esc(item.started_at)}</small></td><td>${item.extraction_state==='extracted'?'Extracted · ':''}${esc(title(item.state))}</td><td>${esc(item.code?message(item.code):item.template_version||'Source retained for review')}</td><td>${item.staged_ids.map(id=>`<button class="secondary compact" data-intake-stage="${id}">Open draft ${id}</button>`).join(' ')}</td></tr>`).join('')}</tbody></table></div></section>`+
    `<details class="panel" id="quality-panel"><summary>Local extraction quality</summary><p>This report uses fixed built-in template identifiers; other layouts are grouped as unknown. Inspect private layouts and their correction history in Provider Management, where a new version requires local validation and explicit activation. Templates never update themselves.</p><button class="secondary" id="quality-refresh">Show quality counts</button><div id="quality-counts"></div><a href="/api/intake/quality/export">Download extraction quality counts</a><p class="caption">Review before sharing. This report contains fixed template/field identifiers and counts, with no document values or source regions. Operational diagnostics remain separate.</p></details>`;
  $('#intake-picker').onclick=ctx.openImport;
  $$('[data-intake-stage]').forEach(button=>button.onclick=()=>ctx.openStage(Number(button.dataset.intakeStage)));
  $('#inbox-config').onsubmit=async e=>{e.preventDefault();try{await api('/intake/configuration',{method:'POST',body:{directory:$('[name=directory]').value,acknowledge:$('#inbox-location-ack').checked}});toast('Local inbox location saved.');ctx.navigate('inbox');}catch(error){$('#inbox-config-error').innerHTML=notice(message(error.message),'danger');}};
  let scanCursor=0;
  $('#scan-inbox').onclick=async()=>{
    const button=$('#scan-inbox'),target=$('#scan-results');button.disabled=true;target.textContent='Processing local files…';
    try{const result=await api('/intake/scan',{method:'POST',body:{directory:data.configuration.directory,acknowledge:$('#inbox-scan-ack').checked,synthetic:ctx.mode==='demo',cursor:scanCursor}});target.innerHTML=result.results.map(item=>`<p>${esc(item.filename)} · ${esc(title(item.state))}${item.code?` · ${esc(message(item.code))}`:''}</p>`).join('')||notice('No supported files found.');scanCursor=result.next_cursor??0;button.textContent=result.remaining?'Scan next files':'Scan Inbox';if(result.remaining)target.innerHTML+=notice(`${result.remaining} additional files remain. Scan next files to continue.`,'warning');target.innerHTML+='<button class="secondary" id="refresh-intake">Refresh intake history</button>';$('#refresh-intake').onclick=()=>ctx.navigate('inbox');}
    catch(error){target.innerHTML=notice(message(error.message),'danger');}finally{button.disabled=false;}
  };
  $('#quality-refresh').onclick=async()=>{try{const result=await api('/intake/quality');$('#quality-counts').innerHTML=`<div class="table-scroll"><table><thead><tr><th>Provider / template</th><th>Observation</th><th>Field</th><th>Count</th><th>Candidate improvement</th></tr></thead><tbody>${result.rows.map(row=>`<tr><td>${esc(row.provider_key)}<small>${esc(row.template_version)}</small></td><td>${esc(title(row.kind))}</td><td>${esc(title(row.field))}</td><td>${row.count}</td><td>${row.candidate_improvement?'Review template':'—'}</td></tr>`).join('')}</tbody></table></div>`;}catch(error){toast(message(error.message),true);}};
}
