import {api,message} from './api.js';
import {$,$$,esc,title,header,empty,notice,field,toast,openDialog,closeDialog} from './ui.js';
export async function showInventory(container,ctx){
  const data=await api('/inventory');
  container.innerHTML=header('Utility inventory','Building, meter, and account relationships established during bill review.')+
    notice('These are recorded service points. Facilities must confirm physical coverage, shared meters, and any closed accounts before treating the inventory as complete.')+
    (!data.meters.length?empty('No service points yet','Approve the first bill to create its provider, account, meter, and optional building mapping.'):
    `<section class="panel table-panel"><div class="section-heading"><h2>Meters and fuel delivery points</h2><span class="muted">${data.meters.length} recorded</span></div><div class="table-scroll"><table><thead><tr><th>Service point</th><th>Building</th><th>Utility</th><th>Unit</th><th></th></tr></thead><tbody>${data.meters.map(m=>`<tr><td><strong>${esc(m.code)}</strong></td><td>${esc(m.building||'Unassigned / shared')}</td><td>${esc(title(m.commodity))}</td><td>${esc(m.unit)}</td><td><button class="secondary compact" data-map="${m.id}">Edit mapping</button></td></tr>`).join('')}</tbody></table></div></section>
    <section class="panel table-panel"><div class="section-heading"><h2>Utility accounts</h2><span class="muted">Staff-owned labels</span></div><div class="table-scroll"><table><thead><tr><th>Provider</th><th>Account label</th><th>Linked service points</th></tr></thead><tbody>${data.accounts.map(a=>`<tr><td>${esc(a.provider)}</td><td>${esc(a.alias)}</td><td>${a.meter_count}</td></tr>`).join('')}</tbody></table></div></section><p class="caption">Meters have their own identifiers. Account-to-meter associations retain observed service dates. Account labels can avoid full supplier account numbers.</p>`);
  container.insertAdjacentHTML('beforeend',`<section class="panel"><h2>Building labels</h2>${data.buildings.map(b=>`<p>${esc(b.name)} <button class="secondary compact" data-building="${b.id}">Rename building</button></p>`).join('')}<p class="caption">Current labels and meter mappings apply to all reported periods. Original approved review values are retained in invoice history. To correct the meter or account on an invoice, use an invoice correction; account links retain all observed service history.</p></section><section class="panel"><h2>Mapping history</h2>${data.history.length?`<ul>${data.history.map(h=>`<li>${esc(h.at)} · ${esc(h.kind)} · ${esc(h.before_value||'Unassigned / shared')} → ${esc(h.after_value||'Unassigned / shared')} · ${esc(h.reason)}</li>`).join('')}</ul>`:'<p>No mapping changes recorded.</p>'}</section>`);
  function edit(kind,item){
    const before=kind==='building'?item.name:(item.building||'');
    openDialog(`<h2>${kind==='building'?'Rename building':'Confirm meter mapping'}</h2>${notice('This changes the grouping of current reports, including past invoice months. Prior reviewed invoice fields and this change history remain available. Leave a meter’s building blank when it is shared or unallocated.','warning')}<form id="mapping-form">${field('Building label','value',before,'text','maxlength="120"')}${field('Reason','reason','','text','required maxlength="500"')}<label class="check-label"><input id="mapping-ack" type="checkbox" required><span>I confirmed this mapping and its effect on reporting.</span></label><div id="mapping-error"></div><div class="action-row"><button class="primary" type="submit">Save mapping change</button><button class="secondary" data-close type="button">Close</button></div></form>`);
    $('#mapping-form').onsubmit=async e=>{e.preventDefault();try{await api(`/inventory/${kind}/${item.id}`,{method:'POST',body:{before,value:$('[name=value]').value,reason:$('[name=reason]').value,acknowledge:$('#mapping-ack').checked}});closeDialog();toast('Mapping updated. Original reviews retained.');await ctx.refresh('inventory');}catch(error){$('#mapping-error').innerHTML=notice(message(error.message),'danger');}};
  }
  $$('[data-map]').forEach(b=>b.onclick=()=>edit('meter',data.meters.find(m=>m.id===Number(b.dataset.map))));
  $$('[data-building]').forEach(b=>b.onclick=()=>edit('building',data.buildings.find(v=>v.id===Number(b.dataset.building))));

}
