import {api,message} from './api.js';
import {$,esc,header,notice,icon} from './ui.js';
export async function showSupport(container,ctx){
  const diagnostics=await api('/diagnostics');
  container.innerHTML=header('Privacy & support','Maintain the application while school records stay with staff.')+
    `<div class="support-grid"><section class="panel"><h2>${icon('support')} Local data boundary</h2><dl class="details"><dt>Deployment</dt><dd>Single operator · loopback only</dd><dt>Portal credentials</dt><dd>No portal connector or credential storage</dd><dt>Raw bills and database</dt><dd>Kept in the selected local data directory</dd><dt>Runtime cloud services</dt><dd>None configured</dd><dt>Analytics / telemetry</dt><dd>Disabled; no telemetry endpoint</dd><dt>Student development data</dt><dd>Synthetic fixtures only</dd></dl>${notice('Use a school-managed account and encrypted disk. This pilot has no database-level encryption, school SSO, or multi-user authorization. IT approval is required before real records are used.','warning')}</section>
    <section class="panel"><h2>Safe support export</h2><p>This export contains software versions and fixed feature flags. It excludes bills, amounts, account names, filenames, paths, and credentials.</p><pre class="diagnostics">${esc(JSON.stringify(diagnostics,null,2))}</pre><a href="/api/diagnostics/export" class="primary">Download diagnostic JSON</a><p class="caption">Review the file before sharing. A developer can reproduce an error using a synthetic test case.</p></section></div>
    <section class="panel"><h2>Staff-approved updates</h2><div class="workflow"><div><strong>01</strong><h3>Review the release</h3><p>School IT inspects the code and dependency changes. The release manifest checks file integrity.</p></div><div><strong>02</strong><h3>Back up locally</h3><p>Create a backup of the database and original files. Keep it in school-controlled storage.</p></div><div><strong>03</strong><h3>Apply and verify</h3><p>Staff stage a separate application folder while keeping the data directory separate. Test the demo before opening staff mode.</p></div></div><p class="caption">There is no remote shell or automatic update agent. A checksum alone does not establish who authored a release or make its code safe.</p></section>
    <section class="panel"><h2>Private staff export</h2><p>The ledger export contains approved school records. Keep it within the school’s authorized workflow.</p><a class="secondary" href="/api/ledger/export">Export approved ledger CSV</a><p class="caption">This is a private operational export. Use the diagnostic JSON for developer support.</p></section>`;
  container.insertAdjacentHTML('beforeend',`<section class="panel"><h2>Backup and restore</h2><p>A consistent backup includes the database, retained sources, review history, and local password hash. Keep it in approved local storage.</p><label class="check-label"><input id="backup-ack" type="checkbox"><span>I understand this is a private backup containing all workspace records.</span></label><button class="primary" id="create-backup" disabled>Create local backup</button><div id="backup-result"></div><h3>Restore with the app stopped</h3><p>Lock this workspace, stop its terminal with Ctrl+C, and use the same selected data directory for the restore command. Restore validates the archive and creates a safety backup before replacing the database. Reopen the app and sign in to verify the recovered records.</p><pre class="diagnostics">python run.py restore --mode ${esc(diagnostics.mode)} --data-dir /selected/local/workspace --archive /local/backup.zip --confirm-restore</pre><p class="caption">Use your approved local paths. Installing a new code folder never migrates records automatically. For a schema 1 workspace, school IT must approve and run the backup-first “migrate --confirm-migrate” command before version 0.2.0 can open it. See docs/STAFF_INSTALL_AND_UPDATES.md.</p></section>`);
  $('#backup-ack').onchange=e=>$('#create-backup').disabled=!e.target.checked;
  $('#create-backup').onclick=async()=>{const button=$('#create-backup');button.disabled=true;try{const result=await api('/backups',{method:'POST',body:{acknowledge:$('#backup-ack').checked}});$('#backup-result').innerHTML=`<p>Backup created and retained in this workspace’s local backups folder.</p><a class="secondary" href="${esc(result.download_url)}">Download private backup ZIP</a>`;}catch(error){$('#backup-result').innerHTML=notice(message(error.message),'danger');}finally{button.disabled=!$('#backup-ack').checked;}};

}
