import {api,message} from './api.js';
import {$,$$,esc,title,quantity,header,field,selectField,notice,toast} from './ui.js';

const utc=value=>new Date(value*1000).toISOString().replace('.000Z','Z');
const readingTable=(readings,code='')=>`<div class="table-scroll"><table><thead><tr><th>Meter / semantics</th><th>Start or counter timestamp (UTC)</th><th>Exclusive end (UTC)</th><th class="numeric">Value</th><th>Source quality</th></tr></thead><tbody>${readings.map(r=>`<tr><td>${esc(r.code||code)}<small>${esc(r.semantics==='cumulative'?'Cumulative counter — no derived use':'Interval delta')}</small></td><td>${esc(utc(r.start_utc))}</td><td>${r.semantics==='delta'?esc(utc(r.end_utc)):'—'}</td><td class="numeric">${quantity(r.quantity)} ${esc(r.unit)}</td><td>${esc(r.quality)}</td></tr>`).join('')}</tbody></table></div>`;

export async function showUsage(container,ctx,selected){
  const generation=ctx.generation,current=()=>container.isConnected&&ctx.generation===generation;
  const listing=await api('/usage');
  if(!current())return;
  if(selected){const selectedData=await api(`/usage/${selected}`);if(current())await detail(container,ctx,listing,selectedData,current);return;}
  container.innerHTML=header('Mapped usage files','Operational measurements with explicit source mapping and retained evidence.')+
    notice('Generic CSV import, tested with fictional files. Provider export compatibility remains unverified. Readings are alternative evidence to billed quantities; they never add charges or enter invoice totals.')+
    `<section class="panel"><h2>Import one source meter</h2><p>Choose a UTF-8 CSV with a header row and up to 5,000 readings. Mapping and approval follow upload. Keep billing dates, usage periods and retrieval schedules separate.</p><form id="usage-upload">${field('Usage CSV file','usage-file','','file','accept=".csv" required')}${ctx.mode==='demo'?'<label class="check-label"><input id="usage-synthetic" type="checkbox" required><span>This file contains synthetic data only.</span></label>':''}<button class="primary" type="submit">Upload usage CSV for mapping</button><div id="usage-upload-error" aria-live="polite"></div></form><p><a href="/api/samples/generic-water-usage.csv">Fictional water CSV</a> · Source meter SYN-WATER-01, US_gal, interval delta; select a confirmed water meter.</p><details><summary>Spreadsheet conversion and supported semantics</summary><p>Direct Excel import is unavailable. In a school-approved local spreadsheet tool, inspect a staff-authorized export without enabling macros, formulas or external links. Export only verified literal measurement values as UTF-8 comma-separated CSV. Preserve the original workbook in school storage and record the conversion in the source quality column. Cached formula results alone are not qualified measured data. Do not send school files to an online converter.</p><p>Delta readings need start and exclusive-end timestamps. Cumulative counter readings retain raw counters without deriving or summing consumption. Include explicit ISO time offsets, or declare an IANA time zone for naive timestamps. Ambiguous or nonexistent daylight-saving times require explicit offsets. No unit conversion or building allocation is inferred.</p></details></section>`+
    `<section class="panel table-panel"><div class="section-heading"><h2>Retained imports</h2><span class="muted">Latest 200</span></div><div class="table-scroll"><table><thead><tr><th>Source</th><th>State</th><th>Review</th></tr></thead><tbody>${listing.items.map(item=>`<tr><td>${esc(item.filename)}<small>${esc(item.created_at)}</small></td><td>${esc(title(item.state))}</td><td><button class="secondary" data-usage="${item.id}">Inspect import ${item.id}</button></td></tr>`).join('')}</tbody></table></div>${listing.items.length?'':notice('No mapped usage files retained yet.')}</section>`+
    `<section class="panel table-panel"><div class="section-heading"><h2>Active operational readings</h2><span class="muted">${listing.active_reading_count} distinct readings · latest 100 shown</span></div>${listing.readings.length?readingTable(listing.readings):notice('No operational readings approved. This does not establish zero use.')}<p class="caption">Exact repeated measurements share one reading with multiple retained sources. Units and counter semantics stay separate. No totals combine operational readings and invoice-derived quantities.</p></section>`;
  $$('[data-usage]',container).forEach(button=>button.onclick=()=>ctx.refresh('usage',button.dataset.usage));
  $('#usage-upload').onsubmit=async e=>{e.preventDefault();const button=$('button',e.currentTarget),file=$('[name=usage-file]').files[0];button.disabled=true;try{const result=await api('/usage/import',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Filename':encodeURIComponent(file.name),'X-Synthetic-Data':String(ctx.mode==='demo'&&$('#usage-synthetic').checked)},body:file});if(!current())return;toast(result.duplicate_source?'This exact source was already retained; opening its history.':'Usage source retained. Confirm its mapping.');if(!current())return;await ctx.refresh('usage',result.import_id);}catch(error){if(!current())return;$('#usage-upload-error').innerHTML=notice(message(error.message),'danger');button.disabled=false;}};
}

async function detail(container,ctx,listing,data,current){
  const prior=data.preview?.mapping||{},pending=data.state==='pending';
  const column=(label,name,optional=false)=>selectField(label,name,[[optional?'':'',optional?'Not present / no column':'Choose a source column'],...data.headers.map(x=>[x,x])],prior[name]||'');
  const conflicts=data.conflicts.map(c=>c.import_id?`<li>Conflicting active evidence: <button class="secondary" data-usage="${c.import_id}">Inspect import ${c.import_id}</button></li>`:`<li>${esc(message(c.code))} Keep the XML evidence or reject this mapped import; XML withdrawal is not supported.</li>`).join('');
  container.innerHTML=header(`Usage import ${data.id}`,`${data.filename} · ${title(data.state)}`,`<button class="secondary" id="usage-back">Back to usage files</button>`)+
    (data.source_history.reattempt_of?notice(`New review of unchanged source from import ${data.source_history.reattempt_of}. Reason: ${data.source_history.reason}`):'')+
    notice('Approval confirms the source meter, commodity, unit, timing and measurement meaning. It creates operational evidence only; invoice charges and billed quantities remain unchanged.')+
    `<section class="panel"><div class="section-heading"><h2>Retained source</h2><a href="/api/sources/${data.document_id}" download>Download original CSV</a></div><p>${data.row_count} rows · first ${data.source_rows.length} shown. Source hash: <code class="source-hash">${esc(data.source_sha256)}</code></p><div class="table-scroll"><table><thead><tr>${data.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${data.source_rows.map(row=>`<tr>${data.headers.map(h=>`<td>${esc(row[h])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`+
    (pending?`<section class="panel"><h2>Explicit mapping</h2><form id="usage-mapping"><div class="form-grid two">${selectField('Confirmed local meter','meter_code',[['','Choose a confirmed meter'],...listing.meters.map(m=>[m.code,`${m.code} · ${m.commodity} · ${m.building||'Unassigned / shared'}`])],prior.meter_code||'')}${selectField('Source commodity','commodity',[['','Choose a commodity'],...Object.keys(listing.units).map(x=>[x,title(x)])],prior.commodity||'')}${selectField('Declared source unit','unit',[['','Choose a precise unit'],...Object.values(listing.units).flat().filter((x,i,a)=>a.indexOf(x)===i).map(x=>[x,x])],prior.unit||'')}${selectField('Measurement meaning','semantics',[['','Choose semantics'],['delta','Delta quantity over an interval'],['cumulative','Raw cumulative counter at a timestamp']],prior.semantics||'')}${column('Source meter column','meter_column')}${field('Exact source meter identifier (all rows)','source_meter',prior.source_meter||'')}${column('Start / counter timestamp column','start_column')}${column('Exclusive end column (delta only)','end_column',true)}${column('Measurement value column','value_column')}${column('Source unit column (optional)','unit_column',true)}${column('Source quality column (optional)','quality_column',true)}${field('IANA time zone for naive timestamps (optional)','timezone',prior.timezone||'','text','placeholder="America/New_York"')}</div><p class="caption">US_gal means US gallons. Gas volume and energy remain distinct; unspecified gallons or generic gas units are rejected. The unit column, if selected, must exactly match the declared unit. Missing quality is retained as unknown. Every row must refer to this single source meter. No rows are silently filtered.</p><button class="primary" type="submit">Save mapping and preview readings</button><div id="usage-mapping-error" aria-live="polite"></div></form></section>`:'')+
    (data.preview?`<section class="panel table-panel"><h2>Saved mapping preview · revision ${data.revision}</h2><p>${esc(data.preview.mapping.source_meter)} → ${esc(data.preview.mapping.meter_code)} · ${esc(data.preview.mapping.commodity)} · ${esc(data.preview.mapping.unit)} · ${esc(data.preview.mapping.semantics)} · naive timestamp zone: ${esc(data.preview.mapping.timezone||'none; offsets required')}</p><p>${data.preview.reading_count} distinct source readings; ${data.preview.duplicate_source_rows} repeated source rows collapsed. ${data.duplicate_readings} readings already have identical active evidence. First 20 source readings shown.</p>${readingTable(data.preview.readings,data.preview.mapping.meter_code)}${conflicts?notice('Resolve conflicting evidence before approval. Inspect and explicitly withdraw every conflicting active source with a reason, then reopen this file and preview again. Historical readings and all originals remain retained.','warning')+`<ul>${conflicts}</ul>`:''}${pending?`<form id="usage-approve"><label class="check-label"><input type="checkbox" id="usage-ack" required><span>I verified the original source, meter mapping, units, timestamps, quality and delta/counter semantics. These readings are alternative evidence to billed use.</span></label><button class="primary" type="submit" ${data.conflicts.length?'disabled':''}>Approve operational readings</button><div id="usage-approve-error" aria-live="polite"></div></form>`:''}</section>`:'')+
    (data.decision?`<section class="panel"><h2>Recorded decision</h2><p>${esc(title(data.decision.state))} · ${esc(data.decision.at)}${data.decision.reason?` · ${esc(data.decision.reason)}`:''}</p>${data.withdrawal?`<p>Withdrawn · ${esc(data.withdrawal.at)} · ${esc(data.withdrawal.reason)}</p>`:''}</section>`:'')+
    (!pending&&data.state!=='approved'?`<section class="panel"><h2>Review this retained source again</h2><p>Start a new mapping review of these same original bytes. The earlier decision remains retained.</p><form id="usage-reattempt">${field('Reason for reviewing the same source again','usage-reattempt-reason','','text','required minlength="3" maxlength="500"')}<label class="check-label"><input id="usage-reattempt-ack" type="checkbox" required><span>I confirm a new review of this retained source and will verify its mapping before approval.</span></label><button class="secondary" type="submit">Start new mapping review</button><div id="usage-reattempt-error" aria-live="polite"></div></form></section>`:'')+
    (pending||data.state==='approved'?`<details class="panel"><summary>${pending?'Reject this pending file':'Withdraw this approved source for reconciliation'}</summary><p>${pending?'The file and any mapping previews remain retained.':'This removes the source from active evidence. Exact repeated readings remain active while another approved source supports them. Withdraw all conflicting sources before approving a correction; this action preserves original bytes and history.'}</p><form id="usage-close">${field('Reason','usage-reason','','text','required minlength="3" maxlength="500"')}<label class="check-label"><input id="usage-close-ack" type="checkbox" required><span>I confirm this ${pending?'rejection':'withdrawal'} and its effect on active operational evidence.</span></label><button class="secondary" type="submit">${pending?'Reject pending usage file':'Withdraw approved usage source'}</button><div id="usage-close-error" aria-live="polite"></div></form></details>`:'');
  $('#usage-back').onclick=()=>ctx.refresh('usage');
  $$('[data-usage]',container).forEach(button=>button.onclick=()=>ctx.refresh('usage',button.dataset.usage));
  if(pending){
    const markUnsaved=()=>{const approve=$('#usage-approve button');if(approve){approve.disabled=true;$('#usage-approve-error').innerHTML=notice('The mapping form changed. Save a new preview before approving.','warning');}};
    $('#usage-mapping').addEventListener('input',markUnsaved);$('#usage-mapping').addEventListener('change',markUnsaved);
    $('[name=semantics]').onchange=e=>{if(e.target.value==='cumulative')$('[name=end_column]').value='';};
    $('#usage-mapping').onsubmit=async e=>{e.preventDefault();const button=$('button[type=submit]',e.currentTarget);button.disabled=true;try{const mapping=Object.fromEntries(new FormData(e.currentTarget));await api(`/usage/${data.id}/preview`,{method:'POST',body:{revision:data.revision,mapping}});if(!current())return;await ctx.refresh('usage',data.id);}catch(error){if(!current())return;$('#usage-mapping-error').innerHTML=notice(message(error.message),'danger');button.disabled=false;}};
  }
  if($('#usage-approve'))$('#usage-approve').onsubmit=async e=>{e.preventDefault();const button=$('button',e.currentTarget);button.disabled=true;try{await api(`/usage/${data.id}/approve`,{method:'POST',body:{revision:data.revision,acknowledge:$('#usage-ack').checked}});if(!current())return;toast('Operational readings approved. Invoice totals unchanged.');if(!current())return;await ctx.refresh('usage',data.id);}catch(error){if(!current())return;$('#usage-approve-error').innerHTML=notice(message(error.message),'danger');button.disabled=false;}};
  if($('#usage-reattempt'))$('#usage-reattempt').onsubmit=async e=>{e.preventDefault();const button=$('button',e.currentTarget);button.disabled=true;try{const result=await api(`/usage/${data.id}/reattempt`,{method:'POST',body:{revision:data.revision,reason:$('[name=usage-reattempt-reason]').value,acknowledge:$('#usage-reattempt-ack').checked}});if(!current())return;toast('New mapping review created from retained original bytes.');if(!current())return;await ctx.refresh('usage',result.import_id);}catch(error){if(!current())return;$('#usage-reattempt-error').innerHTML=notice(message(error.message),'danger');button.disabled=false;}};
  if($('#usage-close'))$('#usage-close').onsubmit=async e=>{e.preventDefault();const button=$('button',e.currentTarget);button.disabled=true;try{await api(`/usage/${data.id}/${pending?'reject':'withdraw'}`,{method:'POST',body:{revision:data.revision,reason:$('[name=usage-reason]').value,acknowledge:$('#usage-close-ack').checked}});if(!current())return;toast('Decision retained with source history.');if(!current())return;await ctx.refresh('usage',data.id);}catch(error){if(!current())return;$('#usage-close-error').innerHTML=notice(message(error.message),'danger');button.disabled=false;}};
}
